"""empty message

Revision ID: 3a66a5b5c689
Revises: bb32e42562ee
Create Date: 2025-08-01 08:37:21.239613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a66a5b5c689'
down_revision = 'bb32e42562ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_planet_favorites')
    op.drop_table('user_vehicle_favorites')
    op.drop_table('user_character_favorites')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_character_favorites',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name='user_character_favorites_character_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_character_favorites_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'character_id', name='user_character_favorites_pkey')
    )
    op.create_table('user_vehicle_favorites',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_vehicle_favorites_user_id_fkey'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], name='user_vehicle_favorites_vehicle_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'vehicle_id', name='user_vehicle_favorites_pkey')
    )
    op.create_table('user_planet_favorites',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], name='user_planet_favorites_planet_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_planet_favorites_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'planet_id', name='user_planet_favorites_pkey')
    )
    op.drop_table('favorite')
    # ### end Alembic commands ###
