"""empty message

Revision ID: 4b269036d461
Revises: e57d7188e293
Create Date: 2025-08-01 08:25:12.313701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b269036d461'
down_revision = 'e57d7188e293'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_vehicle_association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_vehicle_association',
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name='character_vehicle_association_character_id_fkey'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], name='character_vehicle_association_vehicle_id_fkey'),
    sa.PrimaryKeyConstraint('character_id', 'vehicle_id', name='character_vehicle_association_pkey')
    )
    # ### end Alembic commands ###
