"""empty message

Revision ID: a15603cbee94
Revises: 3a66a5b5c689
Create Date: 2025-08-01 08:52:15.317348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a15603cbee94'
down_revision = '3a66a5b5c689'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_planet_favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'planet_id')
    )
    op.create_table('user_vehicle_favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'vehicle_id')
    )
    op.create_table('user_character_favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'character_id')
    )
    op.drop_table('favorite')
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_constraint('character_origin_planet_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'planet', ['origin_planet_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('character_vehicle_association', schema=None) as batch_op:
        batch_op.drop_constraint('character_vehicle_association_vehicle_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('character_vehicle_association_character_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'vehicle', ['vehicle_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'character', ['character_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('post_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('post_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('character_vehicle_association', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('character_vehicle_association_character_id_fkey', 'character', ['character_id'], ['id'])
        batch_op.create_foreign_key('character_vehicle_association_vehicle_id_fkey', 'vehicle', ['vehicle_id'], ['id'])

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('character_origin_planet_id_fkey', 'planet', ['origin_planet_id'], ['id'])

    op.create_table('favorite',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vehicle_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name='favorite_character_id_fkey'),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], name='favorite_planet_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorite_user_id_fkey'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], name='favorite_vehicle_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorite_pkey')
    )
    op.drop_table('user_character_favorites')
    op.drop_table('user_vehicle_favorites')
    op.drop_table('user_planet_favorites')
    # ### end Alembic commands ###
